# Generated by Django 5.1.1 on 2024-09-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_orderitem_product_alter_product_collection_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="data",
            new_name="date",
        ),
    ]
